### PR TITLE
Assertbuilder

### PR DESCRIPTION
**Pull request by DanielRose**
Added handling for NUnit.ApplicationDomain.
Throw a more useful exception when no handled unit testing framework is found.

### CODE REVIEW

**Comment by DanielRose** [comment]
Fixes issue #6

**Comment by dhelper** [comment]
Thanks again,

I need to have a look - hopefully later this week (sorry)

**Comment by DanielRose** [comment]
AppVeyor is using NUnit 2.6.3, but the NuGet pacage is 2.6.4 by now.

**Comment by dhelper** [comment]
It's more than that - in that case it should have failed with previous pull.
I want to make sure that there's enough tests and that we do not have dependencies of NUnit/MSTest inside the Core library

**Comment by dhelper** [comment]
Can you update it so that Core would not rely on specific unit testing framework?

 - I prefer it would not need additional dependencies - if I'm using MSTest or a different version on NUnit it should work without conflicts or missing libraries

**Comment by DanielRose** [comment]
It seems that Core previously had a reference to nunit.framework (at least in its NuGet packages), but it was not used. I'll try removing the reference (note that it only gets used in the nunit.core case, and thus the assembly is only loaded in that case).

**Comment by DanielRose** [comment]
Ok, after some testing I found the problem. AppVeyor runs the following command to test:

nunit-console.exe "C:\projects\asserthelper\AssertHelper.Core.Tests\bin\Debug\AssertHelper.Core.Tests.dll" "C:\projects\asserthelper\AssertHelper.NUnit.Tests\bin\Debug\AssertHelper.NUnit.Tests.dll" "C:\projects\asserthelper\AssertHelper.NUnit.Tests\bin\Debug\NUnit.ApplicationDomain.dll"

For some reason, the `NUnit.ApplicationDomain.dll` is taken as a test assembly. When trying to run this as test, NUnit throws the exceptions as seen in the AppVeyor output. Removing that assembly results in a successful test.

**Comment by dhelper** [comment]
I'll remove it from AppVeyor

**Pull request merged**
