### PR TITLE
Fixed Nullable<T> handling

### PR DESCRIPTION
**Pull request by DanielRose**

### CODE REVIEW

**Comment by dhelper** [comment]
Thanks Daniel and welcome to the project :)

**Comment by DanielRose** [comment]
Now an updated NuGet package would be nice :)

**Comment by dhelper** [comment]
Getting there - I have a few more tests (output to fix) and it's out

**Comment by dhelper** [comment]
And it's uploaded to NuGet.org (v1.0.2) - thanks

**Pull request merged**
